package com.nazri.urlshortener.model;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

@DynamoDbBean
public class UrlEntry {

    private String id;
    private String originalUrl;
    private String userId;
    private Long creationDate;
    private Long lastAccessedDate;
    private Long accessCount;
    private Long expirationDate;
    private String customAlias;
    private UrlStatus status;

    @DynamoDbAttribute("id")
    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDbAttribute("originalUrl")
    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    @DynamoDbAttribute("userId")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDbAttribute("creationDate")
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    public Long getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Long creationDate) {
        this.creationDate = creationDate;
    }

    @DynamoDbAttribute("lastAccessedDate")
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)
    public Long getLastAccessedDate() {
        return lastAccessedDate;
    }

    public void setLastAccessedDate(Long lastAccessedDate) {
        this.lastAccessedDate = lastAccessedDate;
    }

    @DynamoDbAttribute("accessCount")
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)
    public Long getAccessCount() {
        return accessCount;
    }

    public void setAccessCount(Long accessCount) {
        this.accessCount = accessCount;
    }

    @DynamoDbAttribute("expirationDate")
    public Long getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(Long expirationDate) {
        this.expirationDate = expirationDate;
    }

    @DynamoDbAttribute("customAlias")
    public String getCustomAlias() {
        return customAlias;
    }

    public void setCustomAlias(String customAlias) {
        this.customAlias = customAlias;
    }

    @DynamoDbAttribute("status")
    public UrlStatus getStatus() {
        return status;
    }

    public void setStatus(UrlStatus status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "UrlEntry{" +
               "id='" + id + '\'' +
               ", originalUrl='" + originalUrl + '\'' +
               ", userId='" + userId + '\'' +
               ", creationDate=" + creationDate +
               ", lastAccessedDate=" + lastAccessedDate +
               ", accessCount=" + accessCount +
               ", expirationDate=" + expirationDate +
               ", customAlias='" + customAlias + '\'' +
               ", status='" + status + '\'' +
               '}';
    }
}
